[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_project = "6asFXwC8aFqnwtyVARHkqg66K5MvigPUPPtS6hHXfT6n"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#wallet = "~/.config/solana/id.json"
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/devnet.json"

[programs.devnet]
anchor_project = "CUGjLcbsRdVcathaUNNSPfzXpGder7pRkMgADzsHji29"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
